### ISSUE TITLE
Install failing: Request to https://github.com/abmaonline/aemsync/tarball/a2bed54 failed

### ISSUE THREAD

**Issue by MehdiDonk** [abmaonline/aemfed#26]
Dear,

I am very new to AEM and trying to install AEMFED returns me the following error:
In the console:
`npm ERR! code SELF_SIGNED_CERT_IN_CHAIN`
`npm ERR! errno SELF_SIGNED_CERT_IN_CHAIN`
`npm ERR! request to https://github.com/abmaonline/aemsync/tarball/a2bed54 failed, reason: self signed certificate in certificate chain``

In the logs:
`certificate chain`
`69 verbose stack     at ClientRequest.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/node-fetch-npm/src/index.js:68:14)`
`69 verbose stack     at ClientRequest.emit (events.js:315:20)`
`69 verbose stack     at TLSSocket.socketErrorListener (_http_client.js:426:9)`
`69 verbose stack     at TLSSocket.emit (events.js:315:20)`
`69 verbose stack     at emitErrorNT (internal/streams/destroy.js:92:8)`
`69 verbose stack     at emitErrorAndCloseNT (internal/streams/destroy.js:60:3)`
`69 verbose stack     at processTicksAndRejections (internal/process/task_queues.js:84:21)`
`70 verbose cwd /Users/mnaqi/Documents/git-repos/aem-wknd/aem-guides-wknd`
`71 verbose Darwin 19.6.0`
`72 verbose argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "aemfed" "--global"`
`73 verbose node v12.18.3`
`74 verbose npm  v6.14.8`
`75 error code SELF_SIGNED_CERT_IN_CHAIN`
`76 error errno SELF_SIGNED_CERT_IN_CHAIN`
`77 error request to https://github.com/abmaonline/aemsync/tarball/a2bed54 failed, reason: self signed certificate in certificate chain``

Any ideas on what is causing this?
I have no clue if I have to signed in somewhere specifically in oder to install AEMFED.

Thank you in advance

**Comment by MehdiDonk** [comment]
Using `sudo npm install aemfed@next --global`solved my issue (see similar ticket #20 )
