### ISSUE TITLE
Can't find localhost instance

### ISSUE THREAD

**Issue by mealtdown** [abmaonline/aemfed#6]
$ npm run dev

> nonbrand.ui.apps@1.0.0 dev C:\Repos\***-landing-page-migration\nonbrand.ui.apps
> run-p scss:watch transpile:watch aemfed

> nonbrand.ui.apps@1.0.0 scss:watch C:\Repos\***-landing-page-migration\nonbrand.ui.apps
> run-p scss:ams:watch scss:amsg:watch

> nonbrand.ui.apps@1.0.0 aemfed C:\Repos\***-landing-page-migration\nonbrand.ui.apps
> aemfed -t "http://admin:admin@localhost:4502" -w "src/main/content/jcr_root/"

> nonbrand.ui.apps@1.0.0 transpile:watch C:\Repos\***-landing-page-migration\nonbrand.ui.apps
> babel src/main/content/jcr_root/apps/***/nonbrand/clientlibs/main/src/js --out-dir src/main/content/jcr_root/apps/***/nonbrand/clientlibs/main/js --source-maps -w

> nonbrand.ui.apps@1.0.0 scss:amsg:watch C:\Repos\***-landing-page-migration\nonbrand.ui.apps
> node-sass -o src/main/content/jcr_root/apps/mnrdlm/nonbrand/clientlibs/***/main/css src/main/content/jcr_root/apps/mnrdlm/nonbrand/clientlibs/***/main/src/scss -w

> nonbrand.ui.apps@1.0.0 scss:ams:watch C:\Repos\***-landing-page-migration\nonbrand.ui.apps
> node-sass -o src/main/content/jcr_root/apps/***/nonbrand/clientlibs/main/css/ src/main/content/jcr_root/apps/***/nonbrand/clientlibs/main/src/scss -w

---------------------------------------
Working dirs: [ 'C:\\Repos\\***-landing-page-migration\\nonbrand.ui.apps\\src\\main\\content\\jcr_root' ]
Targets: http://admin:admin@localhost:4502
Proxy port: 3000
Interval: 100
Exclude:
---------------------------------------
Something missing or not working as expected, open an issue on GitHub: https://github.com/abmaonline/aemfed/issues
---------------------------------------
Scanning: C:\Repos\***-landing-page-migration\nonbrand.ui.apps\src\main\content\jcr_root ...
Awaiting changes ...
---------------------------------------
Failed to check for updates: SyntaxError: Unexpected end of JSON input
Get state for all instances: 425 ms

Read file tree: 101 ms
Build style tree: 123 ms
Successfully compiled 11 files with Babel.
ADD jcr_root/apps/***/nonbrand/clientlibs/main/js/main.js
ADD jcr_root/apps/***/nonbrand/clientlibs/main/js/formfunctions/utility-functions.js
ADD jcr_root/apps/***/nonbrand/clientlibs/main/js/formfunctions/user-form-data.js
ADD jcr_root/apps/***/nonbrand/clientlibs/main/js/formfunctions/modal-functions.js
  Deploying to [localhost:4502] in 71 ms at 2019-05-24T10:51:41.443Z: OK
C:\Repos\***-landing-page-migration\nonbrand.ui.apps\node_modules\browser-sync\dist\index.js:39
    throw new Error("An instance with the name `%s` was not found.".replace("%s", name));
    ^

Error: An instance with the name `localhost:4502` was not found.
    at Function.module.exports.get (C:\Repos\***-landing-page-migration\nonbrand.ui.apps\node_modules\browser-sync\dist\index.js:39:11)
    at Object.reload (C:\Repos\***-landing-page-migration\nonbrand.ui.apps\node_modules\aemfed\lib\bs-wrapper.js:541:39)
    at Pipeline.reloadBrowser [as onPushEnd] (C:\Repos\***-landing-page-migration\nonbrand.ui.apps\node_modules\aemfed\lib\index.js:43:19)
    at sender.send (C:\Repos\***-landing-page-migration\nonbrand.ui.apps\node_modules\aemsync\src\pipeline.js:96:16)
    at IncomingMessage.res.on (C:\Repos\***-landing-page-migration\nonbrand.ui.apps\node_modules\aemsync\src\sender.js:93:7)
    at emitNone (events.js:111:20)
    at IncomingMessage.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1064:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! nonbrand.ui.apps@1.0.0 aemfed: `aemfed -t "http://admin:admin@localhost:4502" -w "src/main/content/jcr_root/"`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the nonbrand.ui.apps@1.0.0 aemfed script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

**Comment by ahmed-musallam** [comment]
I run into this issue often as well, re-running the command usually fixes it. But I am really curious what is causing it.
